#!/bin/bash

#This file tests the first succcess criterion namely, 
#A car can be created and stored in the database

#step 1: create a car using the script create
cd ../
bash create.sh TXM301 nissan red 9

#step 2: check that the licebse file .txt was created
if [ -f "db/TXM301.txt" ]; then
	echo "test one: a txt file was created inside the database: passed"
else
	echo "Test one: Error. File not found: not passed"
fi

#step 3: Check that the car was added to the main file
lastline=$( tail -n 1 db/maincarfile.txt ) 
echo $lastline
if [ "TXM301 nissan red 9" == "$lastline" ];then
	echo "test two: Record was entered correctly: passed"
else
	echo "Test two: Failed"
fi

